# Generated by Django 5.1 on 2024-08-14 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('duty', models.TextField()),
                ('rooms', models.IntegerField()),
                ('meterage', models.IntegerField()),
                ('staff_numbers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField()),
                ('national_code', models.IntegerField(unique=True)),
                ('number', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('how_to_use', models.TextField()),
                ('effects', models.CharField(max_length=255)),
                ('med_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.medicationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('national_code', models.IntegerField(unique=True)),
                ('is_ok', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.department')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.disease')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('how_to_use', models.TextField()),
                ('date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.doctor')),
                ('meds', models.ManyToManyField(related_name='prescriptions', to='my_Ho3PiTaL.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_num', models.IntegerField()),
                ('national_code', models.IntegerField(unique=True)),
                ('number', models.IntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.staffposition')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.patient')),
            ],
        ),
    ]
