# Generated by Django 5.1 on 2024-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Ho3PiTaL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
