# Generated by Django 5.1 on 2024-08-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Ho3PiTaL', '0002_alter_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.AddField(
            model_name='prescription',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.department'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_Ho3PiTaL.disease'),
        ),
    ]
